#!/usr/bin/env python3
"""Generate memory-source cross-checks using the vectors in baseline.S.

T names a case and snapshots the guest ABI registers. A checker saves the
SIMD result, verifies/restores those registers, then calls the C framework.
Update this file rather than hand-editing the generated operand_forms.S.
"""
from pathlib import Path
out=Path(__file__).resolve().parents[1]/'src/tests/operand_forms.S'
H=r'''/* Generated by tools/gen_operand_forms.py; edit the generator.
 * Baseline uses mainly register sources; these cases reuse its expected
 * vectors with memory sources. They add addressing/operand-form coverage,
 * not an independent numerical reference. Intel order: destination, source.
 * T begins a case; CQ/CX compare 64/128 bits; CE compares EAX; CF checks
 * compare flags; CXA4/CXAS allow reciprocal approximation error.
 */
.intel_syntax noprefix
.code32
.section .text
.extern tf_begin
.extern tf_check_u32
.extern tf_check_u64
.extern tf_check_u128
.extern tf_check_approx4
.extern tf_check_approx_scalar
.extern tf_fail_guest_reg

/* Verify that a SIMD probe did not corrupt guest ABI/stack registers. */
.macro T name
 jmp .La\@
.Ln\@: .asciz "\name"
.La\@: push OFFSET FLAT:.Ln\@; call tf_begin; add esp,4
 mov DWORD PTR [of_saved_esp],esp
 mov DWORD PTR [of_saved_ebx],ebx
 mov DWORD PTR [of_saved_ebp],ebp
 mov DWORD PTR [of_saved_esi],esi
 mov DWORD PTR [of_saved_edi],edi
.endm

/*
 * Each checker invokes GUARD first.  If a probe changed ESP or a callee-saved
 * register, this macro restores the complete guarded state and calls
 * tf_fail_guest_reg(name, expected, actual).  It returns ZF=0 on corruption
 * and ZF=1 when all guards are intact.  EAX is preserved on the good path so
 * scalar-conversion result checks remain valid.
 */
.macro GUARD
 cmp esp,DWORD PTR [of_saved_esp]
 jne .Lg_esp\@
 cmp ebx,DWORD PTR [of_saved_ebx]
 jne .Lg_ebx\@
 cmp ebp,DWORD PTR [of_saved_ebp]
 jne .Lg_ebp\@
 cmp esi,DWORD PTR [of_saved_esi]
 jne .Lg_esi\@
 cmp edi,DWORD PTR [of_saved_edi]
 jne .Lg_edi\@
 cmp eax,eax                 /* ZF=1 */
 jmp .Lg_done\@
.Lg_esp\@:
 mov edx,esp
 mov ecx,DWORD PTR [of_saved_esp]
 mov DWORD PTR [of_bad_name],OFFSET FLAT:of_reg_esp
 jmp .Lg_bad\@
.Lg_ebx\@:
 mov edx,ebx
 mov ecx,DWORD PTR [of_saved_ebx]
 mov DWORD PTR [of_bad_name],OFFSET FLAT:of_reg_ebx
 jmp .Lg_bad\@
.Lg_ebp\@:
 mov edx,ebp
 mov ecx,DWORD PTR [of_saved_ebp]
 mov DWORD PTR [of_bad_name],OFFSET FLAT:of_reg_ebp
 jmp .Lg_bad\@
.Lg_esi\@:
 mov edx,esi
 mov ecx,DWORD PTR [of_saved_esi]
 mov DWORD PTR [of_bad_name],OFFSET FLAT:of_reg_esi
 jmp .Lg_bad\@
.Lg_edi\@:
 mov edx,edi
 mov ecx,DWORD PTR [of_saved_edi]
 mov DWORD PTR [of_bad_name],OFFSET FLAT:of_reg_edi
.Lg_bad\@:
 /* Restore before touching the stack or entering C. */
 mov esp,DWORD PTR [of_saved_esp]
 mov ebx,DWORD PTR [of_saved_ebx]
 mov ebp,DWORD PTR [of_saved_ebp]
 mov esi,DWORD PTR [of_saved_esi]
 mov edi,DWORD PTR [of_saved_edi]
 push edx                    /* actual */
 push ecx                    /* expected */
 push DWORD PTR [of_bad_name]
 call tf_fail_guest_reg
 add esp,12
 or edx,1                   /* force ZF=0 */
.Lg_done\@:
.endm

.macro CQ exp
 movq QWORD PTR [of_actual_q],mm0
 GUARD
 jnz .Ldone\@
 push OFFSET FLAT:\exp; push OFFSET FLAT:of_actual_q; call tf_check_u64; add esp,8
.Ldone\@:
.endm
.macro CX exp
 movups XMMWORD PTR [of_actual_x],xmm0
 GUARD
 jnz .Ldone\@
 push OFFSET FLAT:\exp; push OFFSET FLAT:of_actual_x; call tf_check_u128; add esp,8
.Ldone\@:
.endm
.macro CXA4 exp
 movups XMMWORD PTR [of_actual_x],xmm0
 GUARD
 jnz .Ldone\@
 push OFFSET FLAT:\exp; push OFFSET FLAT:of_actual_x; call tf_check_approx4; add esp,8
.Ldone\@:
.endm
.macro CXAS exp
 movups XMMWORD PTR [of_actual_x],xmm0
 GUARD
 jnz .Ldone\@
 push OFFSET FLAT:\exp; push OFFSET FLAT:of_actual_x; call tf_check_approx_scalar; add esp,8
.Ldone\@:
.endm
.macro CE val
 GUARD
 jnz .Ldone\@
 push \val; push eax; call tf_check_u32; add esp,8
.Ldone\@:
.endm
.macro CF val
 /* COMISS/UCOMISS flags must be captured before *any*
    flag-writing guard instruction.  Do not use the guest stack here: if a
    broken emulator corrupted ESP, PUSHFD itself could make the diagnostic
    unsafe.  SETO+LAHF are flag-preserving and capture exactly the flags we
    care about (OF plus SF/ZF/AF/PF/CF). */
 seto BYTE PTR [of_saved_of]
 lahf
 mov BYTE PTR [of_saved_lahf],ah
 GUARD
 jnz .Ldone\@
 movzx eax,BYTE PTR [of_saved_lahf]
 and eax,0x000000d5
 cmp BYTE PTR [of_saved_of],0
 je .Lof_done\@
 or eax,0x00000800
.Lof_done\@:
 push \val; push eax; call tf_check_u32; add esp,8
.Ldone\@:
.endm
.global run_operand_form_suite
run_operand_form_suite:
 /* Also make the outer function resilient to an accumulated stack imbalance. */
 mov DWORD PTR [of_entry_esp],esp
 mov DWORD PTR [of_entry_ebx],ebx
 mov DWORD PTR [of_entry_ebp],ebp
 mov DWORD PTR [of_entry_esi],esi
 mov DWORD PTR [of_entry_edi],edi
'''
# Each row: (case name, input A label, instruction, input B label, expected
# label). Labels are exported by baseline.S; no numeric oracle is computed here.
mmx=[
('PACKSSDW.mem','packssdw_a','packssdw','packssdw_b','exp_packssdw'),
('PACKSSWB.mem','packsswb_a','packsswb','packsswb_b','exp_packsswb'),
('PACKUSWB.mem','packuswb_a','packuswb','packuswb_b','exp_packuswb'),
('PADDB.mem','mm_a','paddb','mm_b','exp_add_wrap'),('PADDD.mem','mm_a','paddd','mm_b','exp_add_wrap'),
('PADDSB.mem','paddsb_a','paddsb','paddsb_b','exp_signed_sat8'),('PADDSW.mem','paddsw_a','paddsw','paddsw_b','exp_signed_sat16'),
('PADDUSB.mem','paddusb_a','paddusb','paddusb_b','exp_all_ff'),('PADDUSW.mem','paddusw_a','paddusw','paddusw_b','exp_all_ff'),('PADDW.mem','mm_a','paddw','mm_b','exp_add_wrap'),
('PAND.mem','mm_a','pand','mm_b','exp_zero_q'),('PANDN.mem','mm_a','pandn','mm_b','mm_b'),('POR.mem','mm_a','por','mm_b','exp_add_wrap'),('PXOR.mem','mm_a','pxor','mm_b','exp_add_wrap'),
('PCMPEQB.mem','mm_a','pcmpeqb','mm_b','exp_zero_q'),('PCMPEQD.mem','mm_a','pcmpeqd','mm_b','exp_zero_q'),('PCMPEQW.mem','mm_a','pcmpeqw','mm_b','exp_zero_q'),
('PCMPGTB.mem','mm_a','pcmpgtb','mm_b','exp_pcmpgtb'),('PCMPGTD.mem','mm_a','pcmpgtd','mm_b','exp_all_ff'),('PCMPGTW.mem','mm_a','pcmpgtw','mm_b','exp_all_ff'),
('PMADDWD.mem','mm_a','pmaddwd','mm_b','exp_pmaddwd'),('PMULHW.mem','mul_signed_a','pmulhw','mul_signed_b','exp_pmulhw_signed'),('PMULLW.mem','mul_signed_a','pmullw','mul_signed_b','exp_pmullw_signed'),
('PSUBB.mem','mm_a','psubb','mm_b','exp_sub_wrap'),('PSUBD.mem','mm_a','psubd','mm_b','exp_sub_wrap'),('PSUBSB.mem','psubsb_a','psubsb','psubsb_b','exp_signed_sat8'),('PSUBSW.mem','psubsw_a','psubsw','psubsw_b','exp_signed_sat16'),('PSUBUSB.mem','psubusb_a','psubusb','psubusb_b','exp_psubusb'),('PSUBUSW.mem','psubusw_a','psubusw','psubusw_b','exp_psubusw'),('PSUBW.mem','mm_a','psubw','mm_b','exp_sub_wrap'),
('PUNPCKHBW.mem','mm_a','punpckhbw','mm_b','exp_punpckhbw'),('PUNPCKHDQ.mem','mm_a','punpckhdq','mm_b','exp_punpckhdq'),('PUNPCKHWD.mem','mm_a','punpckhwd','mm_b','exp_punpckhwd'),('PUNPCKLBW.mem','mm_a','punpcklbw','mm_b','exp_punpcklbw'),('PUNPCKLDQ.mem','mm_a','punpckldq','mm_b','exp_punpckldq'),('PUNPCKLWD.mem','mm_a','punpcklwd','mm_b','exp_punpcklwd'),
('PAVGB.mem','mm_a','pavgb','mm_b','exp_pavgb'),('PAVGW.mem','mm_a','pavgw','mm_b','exp_pavgw'),('PMAXSW.mem','mm_a','pmaxsw','mm_b','mm_a'),('PMAXUB.mem','mm_a','pmaxub','mm_b','mm_a'),('PMINSW.mem','mm_a','pminsw','mm_b','mm_b'),('PMINUB.mem','mm_a','pminub','mm_b','mm_b'),('PMULHUW.mem','mm_a','pmulhuw','mm_b','exp_pmulhuw'),('PSADBW.mem','mm_a','psadbw','mm_b','exp_psadbw')]
lines=[H]
for n,a,op,b,e in mmx:
    lines += [f'    T {n}',f'    movq mm0,QWORD PTR [{a}]',f'    {op} mm0,{"DWORD PTR" if op in ("punpcklbw","punpcklwd","punpckldq") else "QWORD PTR"} [{b}]',f'    CQ {e}']
for op,a,e in [('psllw','mm_a','exp_shift_left1'),('pslld','mm_a','exp_shift_left1'),('psllq','mm_a','exp_shift_left1'),('psraw','shift_signed','exp_shift_arith'),('psrad','shift_signed','exp_shift_arith'),('psrlw','mm_a','exp_shift_right1'),('psrld','mm_a','exp_shift_right1'),('psrlq','mm_a','exp_shift_right1')]:
    lines += [f'    T {op.upper()}.mem-count',f'    movq mm0,QWORD PTR [{a}]',f'    {op} mm0,QWORD PTR [shift_count]',f'    CQ {e}']
lines += ['    T PSHUFW.mem','    pshufw mm0,QWORD PTR [mm_b],0x1b','    CQ exp_pshufw']
lines += ['    T PINSRW.mem16','    movq mm0,QWORD PTR [mm_a]','    pinsrw mm0,WORD PTR [of_word_1234],2','    CQ exp_pinsrw']
lines += ['    emms']

sse_bin=[('ADDPS','addps','xmm_a','xmm_b','exp_addps'),('ADDSS','addss','xmm_a','xmm_b','exp_addss'),('SUBPS','subps','xmm_a','xmm_b','exp_subps'),('SUBSS','subss','xmm_a','xmm_b','exp_subss'),('MULPS','mulps','xmm_a','xmm_b','exp_mulps'),('MULSS','mulss','xmm_a','xmm_b','exp_mulss'),('DIVPS','divps','xmm_a','xmm_b','exp_divps'),('DIVSS','divss','xmm_a','xmm_b','exp_divss'),('MAXPS','maxps','xmm_mix_a','xmm_mix_b','exp_maxps'),('MAXSS','maxss','xmm_a','xmm_b','exp_maxss'),('MINPS','minps','xmm_mix_a','xmm_mix_b','exp_minps'),('MINSS','minss','xmm_a','xmm_b','xmm_a'),('ANDPS','andps','xmm_a','xmm_b','exp_andps'),('ANDNPS','andnps','xmm_a','xmm_b','exp_andnps'),('ORPS','orps','xmm_a','xmm_b','exp_orps'),('XORPS','xorps','xmm_a','xmm_b','exp_xorps'),('UNPCKHPS','unpckhps','xmm_a','xmm_b','exp_unpckhps'),('UNPCKLPS','unpcklps','xmm_a','xmm_b','exp_unpcklps')]
for n,op,a,b,e in sse_bin:
    lines += [f'    T {n}.mem',f'    movaps xmm0,XMMWORD PTR [{a}]',f'    {op} xmm0,'+('DWORD PTR ' if n.endswith('SS') else 'XMMWORD PTR ')+f'[{b}]',f'    CX {e}']
for n,op,src,e,scalar in [('RCPPS','rcpps','xmm_b','exp_rcp',False),('RCPSS','rcpss','xmm_b','exp_rcpss',True),('SQRTPS','sqrtps','xmm_squares','exp_sqrtps',False),('SQRTSS','sqrtss','xmm_squares','exp_sqrtss',True),('RSQRTPS','rsqrtps','xmm_squares','exp_rsqrt',False),('RSQRTSS','rsqrtss','xmm_squares','exp_rsqrts',True)]:
    lines += [f'    T {n}.mem']
    if scalar: lines += ['    movaps xmm0,XMMWORD PTR [xmm_a]']
    mem='DWORD PTR' if scalar else 'XMMWORD PTR'
    lines += [f'    {op} xmm0,{mem} [{src}]',f'    {"CXAS" if scalar and op in ("rcpss","rsqrtss") else "CXA4" if not scalar and op in ("rcpps","rsqrtps") else "CX"} {e}']
# CMP packed/scalar: the eight defined legacy predicates, not all 256 bytes.
for i,e in enumerate(['exp_cmpps0','exp_cmpps1','exp_cmpps2','exp_cmpps3','exp_cmpps4','exp_cmpps5','exp_cmpps6','exp_cmpps7']):
    lines += [f'    T CMPPS.mem.{i}','    movaps xmm0,XMMWORD PTR [xmm_cmp_a]',f'    cmpps xmm0,XMMWORD PTR [xmm_cmp_b],{i}',f'    CX {e}']
for i,e in enumerate(['exp_cmpss0','exp_cmpss1','exp_cmpss2','exp_cmpss3','exp_cmpss4','exp_cmpss5','exp_cmpss6','exp_cmpss7']):
    lines += [f'    T CMPSS.mem.{i}','    movaps xmm0,XMMWORD PTR [xmm_a]',f'    cmpss xmm0,DWORD PTR [xmm_b],{i}',f'    CX {e}']
lines += ['    T COMISS.mem','    movss xmm0,DWORD PTR [xmm_a]','    comiss xmm0,DWORD PTR [xmm_b]','    CF 1','    T UCOMISS.mem','    movss xmm0,DWORD PTR [xmm_a]','    ucomiss xmm0,DWORD PTR [xmm_b]','    CF 1']
lines += ['    T SHUFPS.mem','    movaps xmm0,XMMWORD PTR [xmm_a]','    shufps xmm0,XMMWORD PTR [xmm_b],0x1b','    CX exp_shufps']
lines += ['    T CVTPI2PS.mem','    movaps xmm0,XMMWORD PTR [xmm_a]','    cvtpi2ps xmm0,QWORD PTR [mm_ints]','    CX exp_cvtpi2ps']
lines += ['    T CVTPS2PI.mem','    cvtps2pi mm0,QWORD PTR [xmm_conv]','    CQ exp_cvtps2pi','    T CVTTPS2PI.mem','    cvttps2pi mm0,QWORD PTR [xmm_conv]','    CQ exp_cvttps2pi']
lines += ['    T CVTSI2SS.mem32','    movaps xmm0,XMMWORD PTR [xmm_a]','    cvtsi2ss xmm0,DWORD PTR [of_int_12345]','    CX exp_cvtsi2ss']
lines += ['    T CVTSS2SI.mem32','    cvtss2si eax,DWORD PTR [scalar_3_6]','    CE 4','    T CVTTSS2SI.mem32','    cvttss2si eax,DWORD PTR [scalar_3_6]','    CE 3']
lines += ['    emms','    mov ebx,DWORD PTR [of_entry_ebx]','    mov ebp,DWORD PTR [of_entry_ebp]','    mov esi,DWORD PTR [of_entry_esi]','    mov edi,DWORD PTR [of_entry_edi]','    mov esp,DWORD PTR [of_entry_esp]','    ret']
lines += [r'''
.section .data
.align 16
of_actual_x: .zero 16
.align 8
of_actual_q: .zero 8
of_word_1234: .word 0x1234
.align 4
of_int_12345: .long 12345
of_saved_esp: .long 0
of_saved_ebx: .long 0
of_saved_ebp: .long 0
of_saved_esi: .long 0
of_saved_edi: .long 0
of_entry_esp: .long 0
of_entry_ebx: .long 0
of_entry_ebp: .long 0
of_entry_esi: .long 0
of_entry_edi: .long 0
of_bad_name: .long 0
of_saved_lahf: .byte 0
of_saved_of: .byte 0
of_reg_esp: .asciz "ESP"
of_reg_ebx: .asciz "EBX"
of_reg_ebp: .asciz "EBP"
of_reg_esi: .asciz "ESI"
of_reg_edi: .asciz "EDI"
''']
out.write_text('\n'.join(lines))
print(out)
