#!/usr/bin/env python3
"""Generate literal imm8 instructions and four 8-by-8 register matrices.

Edit this generator, then regenerate src/tests/generated_ops.S. The C suites
compute the expected answers; this file emits only the assembly probes.
"""
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "src/tests/generated_ops.S"

def table_dispatch(name, preload, inst, store, arg_setup):
    # Runtime EAX selects a table entry, but each target contains a literal
    # immediate byte. Passing a variable to one instruction would not test
    # all encodings. Saving EBX moves cdecl argument 1 from [esp+4] to [esp+8].
    s=[]
    s += [".align 16", f".global {name}", f"{name}:", "    push ebx"]
    s += [f"    {x}" for x in arg_setup]
    s += [f"    {x}" for x in preload]
    s += ["    and eax, 0xff", f"    jmp DWORD PTR [{name}_table + eax*4]"]
    for i in range(256):
        s += [f".L{name}_{i}:", f"    {inst.format(i=i)}", f"    jmp .L{name}_store"]
    s += [f".L{name}_store:"] + [f"    {x}" for x in store] + ["    pop ebx", "    ret"]
    s += [".section .rodata", ".align 16", f"{name}_table:"]
    for i in range(256): s += [f"    .long .L{name}_{i}"]
    s += [".section .text"]
    return "\n".join(s)

parts=["""/* Generated by tools/gen_cases.py; edit the generator, not this file.
 * Each imm8 dispatcher masks its index to 0..255 and jumps to an instruction
 * with that literal byte. Shared tails store the result and restore cdecl
 * registers. C references and case names are in immediates.c.
 * Register matrices at the end store pair (dst,src) at index dst*8+src;
 * register_edges.c checks their results. Intel syntax: destination, source.
 */""", ".intel_syntax noprefix", ".code32", ".section .text"]
parts.append(table_dispatch(
    "asm_shufps_imm",
    ["movups xmm0, XMMWORD PTR [edx]", "movups xmm1, XMMWORD PTR [ecx]"],
    "shufps xmm0, xmm1, {i}",
    ["movups XMMWORD PTR [ebx], xmm0"],
    ["mov eax, DWORD PTR [esp + 8]", "mov edx, DWORD PTR [esp + 12]", "mov ecx, DWORD PTR [esp + 16]", "mov ebx, DWORD PTR [esp + 20]"]))
parts.append(table_dispatch(
    "asm_pshufw_imm",
    ["movq mm0, QWORD PTR [edx]"],
    "pshufw mm0, mm0, {i}",
    ["movq QWORD PTR [ebx], mm0", "emms"],
    ["mov eax, DWORD PTR [esp + 8]", "mov edx, DWORD PTR [esp + 12]", "mov ebx, DWORD PTR [esp + 16]"]))

for op in ["psllw","pslld","psllq","psrlw","psrld","psrlq","psraw","psrad"]:
    parts.append(table_dispatch(
        f"asm_{op}_imm",
        ["movq mm0, QWORD PTR [edx]"],
        f"{op} mm0, {{i}}",
        ["movq QWORD PTR [ebx], mm0", "emms"],
        ["mov eax, DWORD PTR [esp + 8]", "mov edx, DWORD PTR [esp + 12]", "mov ebx, DWORD PTR [esp + 16]"]))

# PEXTRW returns the zero-extended word in EAX (the C integer return register).
# Encode all 256 bytes, even though only the low two bits select an MMX word.
s=[".align 16", ".global asm_pextrw_imm", "asm_pextrw_imm:", "    mov eax, DWORD PTR [esp + 4]", "    mov edx, DWORD PTR [esp + 8]", "    movq mm0, QWORD PTR [edx]", "    and eax,0xff", "    jmp DWORD PTR [asm_pextrw_imm_table + eax*4]"]
for i in range(256): s += [f".Lpex_{i}:", f"    pextrw eax, mm0, {i}", "    emms", "    ret"]
s += [".section .rodata", ".align 16", "asm_pextrw_imm_table:"] + [f"    .long .Lpex_{i}" for i in range(256)] + [".section .text"]
parts.append("\n".join(s))

# PINSRW reads the low word of ECX, with the same two-bit lane selector.
s=[".align 16", ".global asm_pinsrw_imm", "asm_pinsrw_imm:", "    push ebx", "    mov eax, DWORD PTR [esp + 8]", "    mov edx, DWORD PTR [esp + 12]", "    mov ecx, DWORD PTR [esp + 16]", "    mov ebx, DWORD PTR [esp + 20]", "    movq mm0, QWORD PTR [edx]", "    and eax,0xff", "    jmp DWORD PTR [asm_pinsrw_imm_table + eax*4]"]
for i in range(256): s += [f".Lpins_{i}:", f"    pinsrw mm0, ecx, {i}", "    jmp .Lpins_store"]
s += [".Lpins_store:", "    movq QWORD PTR [ebx], mm0", "    emms", "    pop ebx", "    ret", ".section .rodata", ".align 16", "asm_pinsrw_imm_table:"] + [f"    .long .Lpins_{i}" for i in range(256)] + [".section .text"]
parts.append("\n".join(s))

OUT.write_text("\n\n".join(parts)+"\n")
print(OUT)

# Append register-index / alias matrices. These are emitted after the immediate dispatchers.
# Reload inputs for each pair so one result cannot become the next input.
# If i==j, load once and operate on the same register; this is an alias case,
# not a two-operand case with coincidentally equal values. Output is row-major.
with OUT.open("a") as f:
    f.write("\n.intel_syntax noprefix\n.code32\n.section .text\n")
    f.write("\n.global asm_xmm_xor_matrix\nasm_xmm_xor_matrix:\n    push ebx\n    push esi\n    mov esi,DWORD PTR [esp+12]\n    mov ebx,DWORD PTR [esp+16]\n")
    idx=0
    for i in range(8):
        for j in range(8):
            f.write(f"    movups xmm{i}, XMMWORD PTR [esi+{i*16}]\n")
            if i != j:
                f.write(f"    movups xmm{j}, XMMWORD PTR [esi+{j*16}]\n")
            f.write(f"    xorps xmm{i}, xmm{j}\n    movups XMMWORD PTR [ebx+{idx*16}], xmm{i}\n")
            idx += 1
    f.write("    pop esi\n    pop ebx\n    ret\n")

    f.write("\n.global asm_xmm_add_matrix\nasm_xmm_add_matrix:\n    push ebx\n    push esi\n    mov esi,DWORD PTR [esp+12]\n    mov ebx,DWORD PTR [esp+16]\n")
    idx=0
    for i in range(8):
        for j in range(8):
            f.write(f"    movups xmm{i}, XMMWORD PTR [esi+{i*16}]\n")
            if i != j:
                f.write(f"    movups xmm{j}, XMMWORD PTR [esi+{j*16}]\n")
            f.write(f"    addps xmm{i}, xmm{j}\n    movups XMMWORD PTR [ebx+{idx*16}], xmm{i}\n")
            idx += 1
    f.write("    pop esi\n    pop ebx\n    ret\n")

    f.write("\n.global asm_mmx_xor_matrix\nasm_mmx_xor_matrix:\n    push ebx\n    push esi\n    mov esi,DWORD PTR [esp+12]\n    mov ebx,DWORD PTR [esp+16]\n")
    idx=0
    for i in range(8):
        for j in range(8):
            f.write(f"    movq mm{i}, QWORD PTR [esi+{i*8}]\n")
            if i != j:
                f.write(f"    movq mm{j}, QWORD PTR [esi+{j*8}]\n")
            f.write(f"    pxor mm{i}, mm{j}\n    movq QWORD PTR [ebx+{idx*8}], mm{i}\n")
            idx += 1
    f.write("    emms\n    pop esi\n    pop ebx\n    ret\n")

    f.write("\n.global asm_mmx_paddb_matrix\nasm_mmx_paddb_matrix:\n    push ebx\n    push esi\n    mov esi,DWORD PTR [esp+12]\n    mov ebx,DWORD PTR [esp+16]\n")
    idx=0
    for i in range(8):
        for j in range(8):
            f.write(f"    movq mm{i}, QWORD PTR [esi+{i*8}]\n")
            if i != j:
                f.write(f"    movq mm{j}, QWORD PTR [esi+{j*8}]\n")
            f.write(f"    paddb mm{i}, mm{j}\n    movq QWORD PTR [ebx+{idx*8}], mm{i}\n")
            idx += 1
    f.write("    emms\n    pop esi\n    pop ebx\n    ret\n")
